services:
#main database service
  mongodb:
    image: 'mongo:6.0'
    container_name: mongodb
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: anand
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - spring-boot-mongo-net
# Datbase GUI service
  mongo-express:
    image: 'mongo-express:1.0.0'
    container_name: mongo-express
    # restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: anand
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: 'mongodb://anand:secret@mongodb:27017/'
    depends_on:
      - mongodb
    networks:
      - spring-boot-mongo-net
# Redis service for caching
  redis:
    image: 'redis:7.2'
    container_name: redis
    # restart: always
    ports:
      - '6379:6379'
    networks:
      - spring-boot-mongo-net


volumes:
  mongo-data:

networks:
  spring-boot-mongo-net:
