

services:
  # --- Java 17 Spring Boot Application ---
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: spring-boot-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATA_MONGODB_URI=mongodb://anand:secret@mongodb:27017/admin
  #     - SPRING_DATA_REDIS_HOST=redis
  #     - SPRING_DATA_REDIS_PORT=6379
  #   depends_on:
  #     mongodb:
  #       condition: service_started
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - spring-boot-mongo-net
  #   restart: always

  # --- Database: PostgreSQL ---
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=golden_pearl_db
      - POSTGRES_USER=anand
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anand -d golden_pearl_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - postgres


  # --- Cache: Redis ---
  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - spring-boot-postgres-net
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
    volumes:
      - redis-data:/data
  dozzle:
    image: amir20/dozzle:latest
    container_name: growkaro-dozzle
    ports:
      - "9999:8080"
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data:
  redis-data:

networks:
  spring-boot-postgres-net:
    driver: bridge